POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
	createVenue(venueInput: 
		{
			name: "Dublin Park"
		}) 
	{
		_id
		name
		longName
		latitude
		longitude
		url
		poc
		street1
		street2
		city
		state
		zipcode
		country
		children
		createdAt
		updatedAt
  }
}
