POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
	createUser(userInput:
		{
			username: "brainy",
			firstName: "Brainy",
			lastName: "Smurf",
			email: "brainy@smurf.com",
			password: "password"
		})
	{
		_id
		username
		email
	}
}
