POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
	createUser(userInput:
		{
			username: "brainy2",
			firstName: "Brainy",
			lastName: "Smurf",
			email: "brainy2@smurf.com",
			password: "password"
		})
	{
		_id
		username
		firstName
		lastName
		email
		createdAt
		updatedAt
	}
}
