POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
	createPOC(pocInput: 
		{
			name: "Joe Bob"
		}) 
	{
		_id
		name
		email
		phone
		createdAt
		updatedAt
  }
}
