POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

query {
  getUsers(perPage: 1, page: 1) {
    items {
			_id
			username
			firstName
			lastName
			email
			createdAt
			updatedAt
		}
    total
	}
}