POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

query {
  getVenues {
    total
    items {
			_id
			name
			longName
			latitude
			longitude
			url
			poc {
				_id
				name
				email
				phone
			}
			street1
			street2
			city
			state
			zipcode
			country
			parent
			createdAt
			updatedAt
		}
	}
}