POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

query {
  getVenue(_id: "607cd91c0af32205fa79ed5c") {
		_id
		name
		longName
		latitude
		longitude
		url
		poc {
      _id
    }
		street1
		street2
		city
		state
		zipcode
		country
		parent
		createdAt
		updatedAt
	}
}