POST http://localhost:8080/graphql
Content-Type: application/json
X-Request-Type: GraphQL

query {
  getVenues {
    items {
			_id
			name
			longName
			streetAddress
			latitude
			longitude
			url
			poc
			children
			createdAt
			updatedAt
		}
    total
	}
}